# Copyright (c) 2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v2 or later

name: Run Python test suite

on:
- pull_request
- push

jobs:
  python_test_suite:
    name: Run Python test suite
    strategy:
      matrix:
        python-version: [3.9, 3.13]  # no particular need for in-between versions
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |-
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes -V \
              grub-common \
              mtools \
              xorriso
          python3 -m venv venv/
          source venv/bin/activate
          pip3 install -r requirements.txt
          pip3 check
          diff -u0 <(pip3 freeze | sed 's,_,-,g' | sort -f) <(sed -e '/^#/d' -e '/^$/d' requirements.txt | sort -f)

      - name: Run Python test suite
        run: |-
          set -x
          source venv/bin/activate
          coverage run -m pytest -v -s
          coverage report
